branches:
  - name: master
  - name: dev
  - name: feature/*
  - name: hotfix/*

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/npm"
  - "@semantic-release/github"
  - "@semantic-release/git"

preset: "conventionalcommits"

tagFormat: "v${version}"

releaseRules:
  - type: docs
    scope: README
    release: patch
  - type: chore
    release: false
  - type: ci
    release: false

# Git commit message format
commitMessage: "chore(release): ${nextRelease.version} [skip ci]"