apiVersion: v1
kind: Service
metadata:
  name: {{ include "generic-chart.fullname" . }}-service
  labels:
  {{- include "generic-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: python-microservice
    {{- include "generic-chart.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.service.ports | toYaml | nindent 2 }}
