name: Lint and Test Helm Charts
permissions:
      contents: read
      packages: write
on:
  pull_request:
  push:
    branches:
      - master  # Trigger for push to the 'master' branch (including merges)

jobs:
  lint-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Run Helm Lint
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Run helm lint on your chart directory
          helm lint ./generic-chart

  push-helm-image:
    runs-on: ubuntu-latest
    needs: lint-test  # Ensure this job runs after lint-test job
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Log in to GitHub Container Registry (GHCR)
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io --username "${{ github.actor }}" --password-stdin


      - name: Set Repository Name in Lowercase
        run: echo "REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Generate Short SHA
        run: echo "SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-4)" >> $GITHUB_ENV

      - name: Package Helm Chart
        run: helm package ./generic-chart --destination .

      - name: Push Helm Chart to GHCR
        run: |
          helm push generic-chart-*.tgz oci://ghcr.io/frankpromise/helmtesting-ct
