name: Lint and Test Helm Charts

on:
  pull_request:
  push:
    branches:
      - master  # Trigger for push to the 'master' branch (including merges)
jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Chart Testing Tool
        uses: helm/chart-testing-action@v2.3.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
            changed=$(ct list-changed --config ct.yaml)
            if [[ -n "$changed" ]]; then
            echo "{changed}={true}" >> $GITHUB_OUTPUT
            fi

      - name: Always Lint Charts (Regardless of Changes)
        run: ct lint --config ct.yaml ${{ github.sha }}

      - name: Lint Changed Charts (Only if Changes Detected)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct lint --config ct.yaml ${{ github.sha }}

  push-helm-image:
    runs-on: ubuntu-latest
    needs: lint-test  # Ensure this job runs after lint-test job
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Helm OCI Support
        run: |
          helm registry login ghcr.io --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}

      - name: Package and push Helm Chart as OCI Image
        run: |
          # Define variables
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-4)
          REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
          
          # Package the Helm chart
          helm package ./generic-chart --version 0.1.0-$SHORT_SHA

          # Push the Helm chart as an OCI image
          helm push generic-chart-0.1.0-$SHORT_SHA.tgz oci://ghcr.io/$REPO_NAME
