name: Lint and Test Helm Charts

on:
  push:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Chart Testing Tool
        uses: helm/chart-testing-action@v2.3.1

      - name: Detect Changed Charts
        id: list-changed
        run: |
          changed=$(ct list-changed --config ct.yaml)
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Lint Changed Charts
        if: steps.list-changed.outputs.changed == 'true'
        run: ct lint --config ct.yaml
