name: Lint, Test, and Push Helm Chart

on:
  push:
    branches:
      - master  # Trigger on push to master

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Package Helm Chart
        run: helm package ./generic-chart --destination .

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_PAT }}" | helm registry login ghcr.io --username "${{ github.actor }}" --password-stdin

      - name: Push Helm Chart to GHCR
        run: |
          helm push generic-chart-*.tgz oci://ghcr.io/${{ github.repository }}
