name: Lint and Test Helm Charts

on:
  pull_request:
  push:
    branches:
      - master  # Trigger for push to the 'master' branch (including merges)
jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Chart Testing Tool
        uses: helm/chart-testing-action@v2.3.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
            changed=$(ct list-changed --config ct.yaml)
            if [[ -n "$changed" ]]; then
            echo "{changed}={true}" >> $GITHUB_OUTPUT
            fi

      - name: Run chart-testing (lint)
        run: ct lint --config ct.yaml